### ISSUE TITLE
Nutzen des Raspi3 BT-Moduls

### ISSUE THREAD

**Issue by mschlenstedt** [Woersty/LoxBerry-Plugin-BLE-Scanner#10]
Habe den Wunsch per PN im Forum bekommen. Geht ja aktuell anscheinend nicht - vielleicht kann man das noch mit unterstützen, falls technisch möglich?

Grüße,
Micha

**Comment by Woersty** [comment]
Klar geht das. Benutze es doch selbst auch.

**Comment by mschlenstedt** [comment]
Stimmt - ich hatte das mit diesem Satz verwechselt: "Die Anwesenheit über das Bluetooth-Signal von Smartphones funktioniert nicht!".

Die Anfrage kam von hismastersvoice aus dem Forum - vielleicht weil es unter den getesteten Sticks im Wiki nicht auftaucht. Ich schreib's ihm, dass er es verwenden kann :-)

Mach zu hier! Danke.

**Comment by Woersty** [comment]
Muss im LoxBerry Hauptrepository behoben werden
