### ISSUE TITLE
"error":"Error reading general config!"

### ISSUE THREAD

**Issue by fflyerm** [Woersty/LoxBerry-Plugin-BLE-Scanner#11]
Hi,
wenn ich das
http://192.168.2.114/plugins/ble_scanner/?mode=normal

im Browser eingebe bekomme ich folgende Fehlermeldung:
{"error":"Error reading general config!","result":"Cannot open general.cfg config file for reading."}

Hat jamnd eine Idee was das sein könnte??

Danke & Grüße,
Michael

**Comment by Woersty** [comment]
Würde sagen die general.cfg ist nicht da, leer oder hat falsche Rechte aber der Rest vom Loxberry geht? Komisch.

**Comment by fflyerm** [comment]
Hi,
doch ist da und steht auch was drin. Ich hab zum Test mal 777 drauf gemacht. Die Datei gehört Loxberry:loxberry.
Ja der Rest funzt einwandfrei.

Grüße,
Michael

**Comment by Woersty** [comment]
Mmh. Wüsste ich gerade nicht woran es liegt.
Muss mal im Quellcode schauen wann genau der Fehler ausgegeben wird und auf was er da prüft.
Bin aber momentan unterwegs...

**Comment by fflyerm** [comment]
Hi,
ok. Kein Stress. Ich auch :-)

Danke
Michael

**Comment by Woersty** [comment]
PHP kann die Konfig nicht lesen.
Siehe hier: https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/blob/master/webfrontend/html/index.php#L136 

Wäre zu prüfen, warum.
Kannst du mir deine /config/system/general.cfg mal zumailen? (ohne Passwörter)

**Comment by fflyerm** [comment]
Hi,
hier meine config

; Config::Simple 4.59
; Fri Dec 16 00:49:10 2016

[BINARIES]
UNZIP=/usr/bin/unzip
CHMOD=/bin/chmod
DATE=/bin/date
TAR=/bin/tar
BZIP2=/bin/bzip2
REBOOT=/sbin/reboot
ZIP=/usr/bin/zip
BASH=/bin/sh
NTPDATE=/usr/sbin/ntpdate
GREP=/bin/grep
APT=/usr/bin/apt-get
SENDMAIL=/usr/sbin/sendmail
AWK=/usr/bin/awk
POWEROFF=/sbin/poweroff
MAIL=/usr/bin/mailx
CURL=/usr/bin/curl
GZIP=/bin/gzip
WGET=/usr/bin/wget
SUDO=/usr/bin/sudo

[MINISERVER1]
ADMIN=admin
CLOUDURL=
NOTE=
PASS=********
NAME=MiniServer
USECLOUDDNS=0
PORT=7777
CLOUDURLFTPPORT=
IPADDRESS=192.168.2.10

[NETWORK]
IPADDRESS=192.168.2.114
SSID=
DNS=192.168.2.1
TYPE=manual
INTERFACE=eth0
GATEWAY=192.168.2.1
MASK=255.255.255.0

[BASE]
STARTSETUP=0
LANG=de
MINISERVERS=1
VERSION=0.2.3
CLOUDDNS=dns.loxonecloud.com
INSTALLFOLDER=/opt/loxberry

[TIMESERVER]
ZONE=Europe/Berlin
METHOD=miniserver
SERVER=


Danke & Grüße,

**Comment by fflyerm** [comment]
Hi,
konntest du wegen meiner Konfig schon mal schauen???
Danke & Grüße,
Michael

**Comment by Woersty** [comment]
Nein. Heute Abend schaue ich mal genauer. Beim ersten ansehen sah das normal aus.

**Comment by Woersty** [comment]
Kann das mit deiner Datei nicht nachstellen. Mail mir mal exakt deine Datei zu (nicht hier reinkopieren).
Vielleicht ist da ein Steuerzeichen verquer oder so?
Hat dein PW vielleicht Sonderzeichen?
Das Problem ist bekannt: https://github.com/mschlenstedt/Loxberry/issues/171

**Comment by fflyerm** [comment]
Hallo,

hier die cfg.

Das Passwort zum Miniserver?? Ja das hat Sonderzeichen drin…

 Grüße,

Michael

**Comment by fflyerm** [comment]
Hi,

passwd geändert. Jetzt geht immerhin schon mal der Browser Aufruf. Über den MS geht es noch nicht. Da muss ich nohcmal schauen.


Danke & Grüße,

Michael

**Comment by Woersty** [comment]
Das Problem ist wie gesagt bekannt als #171 beim LoxBerry Hauptrepository
