### ISSUE TITLE
RPi3 Bluetooth Unterstützung

### ISSUE THREAD

**Issue by neminor** [Woersty/LoxBerry-Plugin-BLE-Scanner#12]
Ich habe nun schon den dritten RPi3 mit Loxberry aufgesetzt und jedes mal nach dem Installieren des BLE Plugins erscheint bei Nutzung des internen Bluetooth folgende Fehlermeldung:

> BLE-Scanner - Fehler bei der Suche

> Error reading tags from Daemon tcp://127.0.0.1:12345

> Connection refused

https://www.loxforum.com/filedata/fetch?photoid=73540

Wenn ich hingegen ein Logilink Bluetooth BT00015 Dongle nutze, funktioniert es.

**Comment by neminor** [comment]
Sehe grade das es dazu schon ein Issue gibt:
https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/issues/10
Ich bekomme es nicht zum laufen. Sind zusätzliche Einrichtungsschritte notwendig?
Was ich getan habe:
- Loxberry 2.3 auf SD schreiben
- Loxberry über Wizard einrichten
- BLE Plugin installieren
- Fehler beim Starten des BLE Plugin

**Comment by Woersty** [comment]
```
sudo apt-get -y remove raspberrypi-sys-mods
sudo apt-get -y install raspberrypi-sys-mods
sudo apt-get -y --reinstall install pi-bluetooth
reboot
```

**Comment by WimisBernhard** [comment]
Hallo Woersty,

entschuldige die Frage, aber wie kann ich auf dem Raspberry das Terminal öffnen um die Befehle aus deinem letzten Post einzugeben?
Der Loxberry ist mein erster Kontakt mit Linux...

**Comment by Woersty** [comment]
Putty herunterladen
http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html
Dann die IP vom LoxBerry eingeben und SSH sowie Port 22 wählen
Links bei **Connection - Data** als _Auto-login username_ **loxberry** eintragen
**Open** anklicken
Und dein Shell Passwort eingeben welches bei der Installation vergeben wurde

Grüße

**Comment by WimisBernhard** [comment]
Super!

Hat funktioniert und die Befehle die du oben angegeben hast
funktionieren auch.

Jetzt funktioniert das interne Bluetooth Modul mit dem Loxberry !

Danke

**Comment by Woersty** [comment]
Fein. @mschlenstedt wollte das ja mal in eine kommende Version des LoxBerry einbauen. Dann kann man sich die manuelle Fummelei sparen. Ich verlinke das mal nochmal dorthin: https://github.com/mschlenstedt/Loxberry/issues/46
