### ISSUE TITLE
Fehler: Error, got no results. - keine Aktualisierung Loxone Eingang

### ISSUE THREAD

**Issue by neminor** [Woersty/LoxBerry-Plugin-BLE-Scanner#13]
Wenn alle registrierten Tags außer Reichweite sind, wird im Log folgendes protokolliert:

2017-01-20 14:47:14 [OK] Query: 4 Tag(s) processed [direct]

2017-01-20 14:49:44 Error, got no results.
2017-01-20 14:51:45 Error, got no results.
2017-01-20 14:53:46 Error, got no results.
2017-01-20 15:00:59 Error, got no results.
2017-01-20 16:00:58 Error, got no results.
2017-01-20 16:25:45 [OK] Query: 4 Tag(s) processed [direct]

Es werden in dem Fall keine Aktualisierungen der Loxone Eingänge vorgenommen. Ein Bewohner bleibt also auf Status "Anwesend" obwohl er nicht mehr anwesend ist. 

Wenn sich mindestens ein unregistrierter Tag in Reichweite befindet klappt es problemlos.

**Comment by Woersty** [comment]
Upps. Schaue mir das an.

**Comment by mdettki** [comment]
Diese Fehlerbehandlung kam in der letzten Version hinzu (index.php):
// If no result, abort
 if (!isset($tags_scanned) || $tags_scanned == "null")
{
  error_log( date('Y-m-d H:i:s ')."Error, got no results.", 3, $logfile);
 die(json_encode($tags_scanned));
}
Wenn man diese entfernt funktioniert es wieder und auch die abwesenden GTags werden zurückgemeldet.

**Comment by Woersty** [comment]
Könnt ihr bitte mal die 0.16 testen?
Bei mir erkennt er sporadisch mal den einen oder anderen Tag nicht.
Vielleicht ist das Timeout zu knapp.
Würde mich über eure Erfahrungswerte nach ca. 1 Woche Test freuen.
