### ISSUE TITLE
Virtuelle Eingänge werden nicht geändert

### ISSUE THREAD

**Issue by Aexelomeus** [Woersty/LoxBerry-Plugin-BLE-Scanner#20]
Hallo,

zum Hintergrund:
- Mac-Adressen copy&paste mit BLE_
- die IP-Adresse vom Loxberry wird erreicht
- Tags werden im Loxberry gefunden

Problem: 
- Virtuelle Eingänge werden nicht geändert

Log-Datei:
`2017-10-12 22:24:55 [OK] Query: 2 Tag(s) processed [direct]`
`2017-10-12 22:25:25 [OK] Query: 2 Tag(s) processed [direct]`
`2017-10-12 22:25:54 [OK] Query: 2 Tag(s) processed [direct]`

Da kein error_log 

> "Can not sent Data to Miniserver! Unable..."

erscheint, wird $LoxLink anscheinend richtig geöffnet. Aber es kommt nichts im Miniserver an, zumindest werden die Virtuellen Eingänge nicht geändert.

tcpdump hat leider kein Ergebnis gebracht, also dort gibt es kein Hinweis auf einen String der $LoxURL ähnlich sieht. 

Wie kann ich überprüfen, wie der String hinter $LoxLink aussieht oder warum er nicht aufgerufen wird?!

**Comment by Aexelomeus** [comment]
In der Datei "webfrontend/html/index.php" Zeile 198 der aktuellsten Version steht folgender Code:
`if ( $current_ms[1] == 'ON' )`

diesen habe ich jetzt wie folgt geändert:
`if ( $current_ms[1] == "ON" )`

Mit dieser kleinen Anpassung läuft es jetzt bei mir.

**Comment by Woersty** [comment]
Danke, habe es mal in die v0.24 eingebaut.
