### ISSUE TITLE
 Error reading tags! Reason:UnboundLocalError: local variable 'pkt' referenced before assignment

### ISSUE THREAD

**Issue by neminor** [Woersty/LoxBerry-Plugin-BLE-Scanner#21]
Seit v0.24 habe ich das Problem dass nach einigen Tagen die Erkennung aussteigt. Es werden keine Tags erkannt. Es wird dann im Plugin-Log:

`2017-11-20 15:01:38 Error reading tags! Reason:UnboundLocalError: local variable 'pkt' referenced before assignment`

ausgegeben. Nach einem Neustart des Loxberry funktioniert es dann wieder.

**Comment by Woersty** [comment]
Mmh. Daran habe ich gar nix geändert. Ich schau mal wenn ich Zeit finde.

**Comment by Woersty** [comment]
Versuch mal die 24.a hier aus dem GitHub. 
Wenn es nicht klappt, nochmal wieder aufmachen den Bug.
Ich habe keine Ahnung ob ich an der richtigen Stelle gefummelt habe.

**Comment by Woersty** [comment]
Link: https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/archive/master.zip

**Comment by neminor** [comment]
sieht gut aus, läuft wieder seit 4 Tagen stabil. Danke
