### ISSUE TITLE
Datenbankfehler?

### ISSUE THREAD

**Issue by vplustute** [Woersty/LoxBerry-Plugin-BLE-Scanner#25]
Wenn ich den BLE Scanner installierte habe, muss ich doch nach G-Tag suchen, oder?
Mir wird dann folgender Fehler angezeigt

DB connect error
Access denied for user 'ble_scanner'@'localhost' (using password: YES)

Wo liegt hier der Fehler?

**Comment by Woersty** [comment]
Datenbank neu erstellen anklicken.
In der aktuellen Version macht er das noch nicht automatisch.
Kommt aber noch.

**Comment by Dietmar81** [comment]
Bei der Erstellung der Datenbank bekomme ich folgenden Fehler:
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'ble_scanner'@'%'

**Comment by vplustute** [comment]
Genau den Fehler bekomme ich auch. Somit kann ich auch keine Datenbank neu erstellen.

**Comment by Woersty** [comment]
Da muss ich noch mal schauen 
Ich glaube ‚if exists‘ geht nicht für drop User .
Melde mich später

**Comment by Woersty** [comment]
Geht das eigentlich jetzt?

**Comment by vplustute** [comment]
Wie soll es denn ohne neue Version funktionieren?
Mit dem was du als letztes geschrieben hast, konnte ich nichts anfangen und ich dachte da wird Versionstechnisch was geändert.
Ich bin jetzt erstmal wieder zur Version 0.23 gewechselt.
Wenn du mir genau sagst, was ich wie testen kann/soll, dann kann ich das auch machen und werde Bericht erstatten.

**Comment by Dietmar81** [comment]
Version 0.23 ist soweit funktionstüchtig? Wo kann ich diese beziehen?

**Comment by Woersty** [comment]
Bei mir läuft sie eigentlich stabil. Jemand meint aber, dass sein Loxberry bei wlan Betrieb abstürzt. Download direkt hier im GitHub.

**Comment by Dietmar81** [comment]
Bräuchte ein wenig Hilfe,.. Bin neu hier...

**Comment by Dietmar81** [comment]
Habe es hinbekommen. Die aktualisierte Version von dir funktioniert. Vielen Dank Wörsty.

**Comment by vplustute** [comment]
Gibt es schon eine aktueller Version?
Die Version 0.30 läuft bei mir definitiv nicht.

**Comment by Dietmar81** [comment]
Ja. Bei mir funktioniert nun das Anlegen der Datenbank und ich kann den Tag empfangen.

**Comment by hagruber** [comment]
HILFE: Komm bei der Version 0.30 nicht über den Fehler "ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'ble_scanner'@'%'" hinweg und finde auf GitHub den Download zur Verison 0.23 nicht wieder?!

**Comment by Dietmar81** [comment]
Es gibt hier schon ne neue Version, die funktioniert.

**Comment by hagruber** [comment]
DANKE. Ich konnte nun die Version 0.31a finden auf GitHub finden und installieren. Trotzdem musste ich den daemon über die Konsole manuell starten damit der Port 12345 geöffnet wurde. Anlegen der Datenbank hat nun funktioniert, aber die Gigaset tags werden immer noch NICHT erkannt/gefunden?

**Comment by Woersty** [comment]
Neu gebootet hast du?

**Comment by hagruber** [comment]
Ja, gebootet habe ich. Allerdings krieg ich nach jedem reboot krieg wieder **"Error0002: Problem reading tags from Daemon tcp://127.0.0.1:12345 Connection refused"**, so dass ich über "**/usr/bin/php -f /opt/loxberry/webfrontend/cgi/plugins/ble_scanner/bin/daemon.php"** den Port manuell öffnen muss... die Gigasettags werden vom LogiLink Dongle im Laptop eingesteckt erkannt, nur mit dem BLE-Scanner via Rasperry scheint's nicht zu funktionieren...

**Comment by Woersty** [comment]
Wieso Dongle? Ist das kein Raspberry 3?
Der hat Bluetooth onboard. 
Das geht nicht mit Dongle.

**Comment by Woersty** [comment]
Ansonsten müsstest du mal schauen, warum das Script BLE-Scanner in \opt\loxberry\system\daemons\plugins nicht läuft.
Log dazu ist /opt/loxberry/log/plugins/ble_scanner/BLE-Scanner.log

**Comment by Woersty** [comment]
Ansehen kannst du das normalerweise unter http://loxberry/plugins/ble_scanner/?mode=show_logfile

**Comment by hagruber** [comment]
Ich krieg den auf Raspberry 3 (intern) vorhandenen Bluetooht device nicht zum laufen -> hcitool dev, devices (leer)... dies fängt schon damit an, dass bei der Installation des Plugins im Logfile der Fehler "Job for hciuart.service failed" erscheint... etc... bis "Failed to start Configure Bluetooth Modems connected by UART"... Weiter geht's mit dem "Error0002: Problem reading tags from Daemon tcp://127.0.0.1:12345 Connection refused", so dass ich über "/usr/bin/php -f /opt/loxberry/webfrontend/cgi/plugins/ble_scanner/bin/daemon.php" den Port manuell öffnen muss... Wie gesagt ein externer Dongle wird einwandfrei erkannt inkl. den Gigasettags, aber damit scheint das Plugin auf Raspberry 3 nicht klar zu kommen... ich denke ich komme mit der aktuellen Linux- bzw. Loxberryversion hier nicht weiter?!

**Comment by Woersty** [comment]
Ich weiß nicht warum das bei dir nicht geht. Ist dein internes Bluetooth vielleicht defekt? 
Kann ich momentan nicht helfen.

**Comment by hagruber** [comment]
Zweites neues Raspberry Pi 3, Model B Board gekauft, gleiches Verhalten bzw. dieselben Fehler... einen "internen Bluetoothdefekt" würde ich damit ausschliessen...

**Comment by Woersty** [comment]
Werde das in der v2018.3.4 lösen. Wird aber nicht abwärtskompatibel sein zum LoxBerry 0.2.x.

**Comment by hagruber** [comment]
Hat funktioniert, vielen Dank.
Grüsse aus der Schweiz.

2018-03-03 23:43 GMT+01:00 Wörsty <notifications@github.com>:
