### ISSUE TITLE
Auch mit Version 0.9 Error reading tags from Daemon tcp://127.0.0.1:12345

### ISSUE THREAD

**Issue by MichaelSigi** [Woersty/LoxBerry-Plugin-BLE-Scanner#3]
Auch mit der Version 0.9 kommt beim Aufruf des Plugin 
"Error reading tags from Daemon tcp://127.0.0.1:12345" Connection refused.
Verwendet wurde ein Raspberry 3.

**Comment by Woersty** [comment]
Raspberry 3 wird erst ab der nächsten Loxberry Version unterstützt.
Mach mal 
sudo apt-get -y remove raspberrypi-sys-mods
sudo apt-get -y install raspberrypi-sys-mods
sudo apt-get -y --reinstall install pi-bluetooth
- reboot

**Comment by MichaelSigi** [comment]
Ok hat geklappt, scheinabr war raspberrypi-sys-mods noch nicht installiert.
Besten Dank für die Arbeit und die schnelle Hilfe.
