### ISSUE TITLE
Can not sent Data to Miniserver!

### ISSUE THREAD

**Issue by Ezechyel** [Woersty/LoxBerry-Plugin-BLE-Scanner#33]
Tag-Name und VI am Miniserver sind korrekt formatiert (MAC-Adresse aus dem Seiten-Quellcode kopiert).
Das Tag ist in Reichweite, die Login-Daten des Miniservers am Loxberry sind ebenfalls richtig, da andere Plugins funktionieren.

Ich habe die MAC-Adressen im Log mit "xx" unkenntlich gemacht.

[BLE-Scanner (1).log](https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/files/2124158/BLE-Scanner.1.log)

**Comment by Woersty** [comment]
Ruf doch die Adresse aus dem Log mal im Browser auf.
Vermutlich gibt es keinen Eingang mit der Bezeichnung "BLE_xx_xx_80_AC_03_60" am Miniserver oder er ist unter der angegebenen Adresse nicht erreichbar.

**Comment by Ezechyel** [comment]
Kann geschlossen werden. Es besteht nach Neuinstallation ein anderer Fehler, Issue dazu folgt.
