### ISSUE TITLE
"Fehler0003: Daemon Prozess läuft (noch) nicht"

### ISSUE THREAD

**Issue by neminor** [Woersty/LoxBerry-Plugin-BLE-Scanner#34]
Ich habe neu einen Pi 3 Modell B+ im Einsatz. Nach dem Installieren und auch mehrmaligen Neustart erscheint:
 "Fehler0003: Daemon Prozess läuft (noch) nicht"

**Comment by Woersty** [comment]
Ohne Logs kann ich nicht erraten, was das Problem ist...

**Comment by neminor** [comment]
systemctl status hciuart.service
â hciuart.service - Configure Bluetooth Modems connected by UART
   Loaded: loaded (/lib/systemd/system/hciuart.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-09-30 09:38:45 CEST; 18min ago

Sep 30 09:38:45 loxberry systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Sep 30 09:38:45 loxberry btuart[925]: Can't get port settings: Input/output error
Sep 30 09:38:45 loxberry btuart[925]: Can't initialize device: Input/output error
Sep 30 09:38:45 loxberry systemd[1]: hciuart.service: Control process exited, code=exited status=1
Sep 30 09:38:45 loxberry systemd[1]: Failed to start Configure Bluetooth Modems connected by UART.
Sep 30 09:38:45 loxberry systemd[1]: hciuart.service: Unit entered failed state.
Sep 30 09:38:45 loxberry systemd[1]: hciuart.service: Failed with result 'exit-code'.

**Comment by neminor** [comment]
hciconfig -a bringt:

hci0: Type: Primary Bus: USB
BD Address: 00:1A:7DA:71:04 ACL MTU: 310:10 SCO MTU: 64:8
UP RUNNING

**Comment by neminor** [comment]
Im Loxberry Log steht:

INFO: LoxBerry Version 1.2.4.5 ( is_raspberry.cfg )
 INFO: BLE-Scanner Version v2018.4.25
 INFO: Loglevel: 3
 CRITICAL: [30-Sep-2018 09:38:45 CEST] Error when starting Bluetooth (hciuart.service) 3rd time. Giving up..

**Comment by neminor** [comment]
more /lib/systemd/system/hciuart.service
[Unit]
Description=Configure Bluetooth Modems connected by UART
ConditionPathIsDirectory=/proc/device-tree/soc/gpio@7e200000/bt_pins
Requires=dev-serial1.device
After=dev-serial1.device

[Service]
Type=forking
ExecStart=/usr/bin/btuart

[Install]
WantedBy=multi-user.target

**Comment by Woersty** [comment]
Tja, schlecht. War früher UART. Jetzt USB. :(

**Comment by neminor** [comment]
Ich habe nen Stick dran:

lsusb
Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 005: ID 0424:7800 Standard Microsystems Corp.
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by Woersty** [comment]
Wenn ich mir den Code ansehe, gehe ich aber eigentlich nur auf hci0 - sollte trotzdem gehen. Weiß nicht warum er deinen service nicht starten kann. Das ist aber eher ein Betriebssystem als Plugin Thema würde ich sagen

**Comment by Woersty** [comment]
Dachte der hat Bluetooth eh onboard

**Comment by neminor** [comment]
ja, aber das interne BT bekomme ich mit dem aktuelle loxberry os nicht zum laufen.
Habe jetzt über die boot/config.txt 

	dtoverlay=pi3-disable-bt
	enable_uart=1

den Stick zum laufen gebracht.

**Comment by Woersty** [comment]
Ok, ich merk's mir falls nochmal jemand stolpert. 👍

**Comment by Dizzy1985** [comment]
Ich hänge mich hier auch mal mit dran.... Habe das selbe Problem mit dem Pi 3 Modell B+
Haben das auch schon im Lox-Forum erörtert.

**Comment by Woersty** [comment]
@Dizzy1985 Funktioniert die Lösung bei dir auch?
