### ISSUE TITLE
Scanning Bluetooth-Tags

### ISSUE THREAD

**Issue by hagruber** [Woersty/LoxBerry-Plugin-BLE-Scanner#36]
Nach mehrmonatigem erfolgreichem Betrieb des Plugins werden zur Zeit die bestehenden Bluetooth-Tags vom Scanner immer wieder als neue "Devices" identifiziert. 
Bei jedem Scan also erzeugt dies neue Zeilen an "angeblich" neuen Devices mit neuen/anderen MAC-Adressen. Damit "greifen" die bestehenden und in der Vergangenheit erfolgreichen "virtuellen Eingangsdefinitionen" des Miniservers ins "Leere". Woran kann das liegen?
Danke im Voraus.

**Comment by Woersty** [comment]
Wüsste ich erstmal nicht, warum das so ist.
Sieht deine ble_scanner.cfg aus \config\plugins\ble_scanner normal aus?
Ansonsten in der Pluginverwaltung mal das Loglevel auf Debug stellen und gucken,
was er macht....

**Comment by hagruber** [comment]
Hallo,
ich hab mal eine Logdatei angehängt, die ich leider nicht im Stande bin zu
interpretieren...
Vielleicht könntes Du mir kurz eine Rückmeldung geben?
Danke im Voraus.

**Comment by Woersty** [comment]
Die Logdatei wird hier im Bug nicht automatisch angefügt.
Am besten mir direkt zusenden.
eMail siehe https://github.com/Woersty/LoxBerry-Plugin-BLE-Scanner/blob/master/plugin.cfg#L10
