### ISSUE TITLE
Spamming of Logfiles

### ISSUE THREAD

**Issue by meteo88** [Woersty/LoxBerry-Plugin-BLE-Scanner#39]
Hi,

i recognized that my logfile is growing very fast until my Loxberry cannot write any files in the tmpfs and i think i found the issue:

Following meassages werde written frequently in both log files (var/log/kern.log and /var/log/syslog):

Jan 27 20:37:12 loxberry kernel: [   91.112104] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:13 loxberry kernel: [   92.453802] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:15 loxberry kernel: [   94.463333] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:16 loxberry kernel: [   95.126927] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:16 loxberry kernel: [   95.470640] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:17 loxberry kernel: [   96.473727] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:18 loxberry kernel: [   97.481215] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:19 loxberry kernel: [   98.486246] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:20 loxberry kernel: [   99.137352] Bluetooth: hci0: advertising data len corrected
Jan 27 20:37:22 loxberry kernel: [  101.492589] Bluetooth: hci0: advertising data len corrected

Is there a way to block this message so that the logfile does not grow that fast?

Best regards,
Dominik

**Comment by Woersty** [comment]
Hi, I will check if there is a possibility to suppress these messages

**Comment by Woersty** [comment]
Versuch mal die PreRelease 2021.2.2

**Comment by meteo88** [comment]
Funktioniert perfekt, danke!! lg Dominik
