### ISSUE TITLE
Loxone Config erkennt den Status nicht korrekt

### ISSUE THREAD

**Issue by Tonphis** [Woersty/LoxBerry-Plugin-BLE-Scanner#8]
Hallo,

ich habe das Problem das bei meinem neu aufgesetzten Loxberry (Rasp2) der BLE-Scanner die Statusänderung nicht korrekt an den Loxone Miniserver sendet.

Ich habe diesen Fehler sowohl mit billig Tags aus China, als auch mit dem Gigaset Tags. 
BLE Scanner ist in der Version 0.14 installiert.

**Comment by Woersty** [comment]
Probiere mal bitte 0.15 und gib mir Bescheid.

Danke

**Comment by Tonphis** [comment]
Hi,

gestern Abend habe ich die Version 0.15 neu installiert. Danach ging es bis heute morgen. Jetzt steht ein Tag allerdings wieder als auf "anwesend"

**Comment by Woersty** [comment]
Was gibt den` hcitool lescan` aus, wenn du es manuell auf der Shell aufrufst?
Das Script nimmt eigentlich nur diese Ausgabe und schickt das dann an den Miniserver weiter,
wenn der TAG und Miniserver ein Häkchen haben.

**Comment by Tonphis** [comment]
Was muss ich den für einen parameter im hcitool scannen? bzw was muss ich im terminal eingeben?

**Comment by Woersty** [comment]
Als root: `hcitool lescan`
Weiter nix

**Comment by Tonphis** [comment]
Hallo, ich noch mal. Habe gerade erst wieder zeit mich mal Hinter das Thema zu klemmen.
Ich bin aktuell abwesend in BLE Plugin stehe ich auch als abwesend aber die Lxone zeigt "anwesend" an.

wenn ich mich mit sudo su anmelden will kommt bei mir folgender Fehlr:
loxberry@loxberry:~ $ sudo su
[sudo] password for loxberry: 
Sorry, user loxberry is not allowed to execute '/bin/su' as root on loxberry.

**Comment by Ezechyel** [comment]
Hallo @Woersty 
bei mir wird in Loxone Config die BLE-Tags als Abwesend angezeigt. 
**Folgende Situation:**
- Die Mac-Adressen sind korrekt und mit Unterstrichen (zur Sicherheit via "Code anzeigen" aus dem HTML kopiert)
- die IP-Adresse vom Loxberry ist korrekt und funktioniert
- Die Tags sind eingeschaltet und verbunden
- Das Plugin zeigt die Tags auch korrekt mit richtigem Status an
- Eingangs- und Ausgangsreferenzen sind korrekt angelegt

**Problem:** Es erfolgt keine Aktualisierung des Status in der Config. Aufällig ist, dass es zuvor einmal funktioniert hat, nun jedoch nicht mehr.

**Meldung von hcitool:**
```
loxberry@loxberry:~ $ hcitool lescan
Set scan parameters failed: Operation not permitted
```
Funktioniert auch mit sudo nicht. Keine Berechtigung.
Hast du eine Idee? Ich habe auch die China-Tags.

Gruß Ezechyel

**Comment by Tonphis** [comment]
Morgen,

Das gleiche Problem hatte ich ja auch. 
Konnte es leider nicht weiter verfolgen weil ich das Root Passwort nicht mehr zur Hand hatte. Werde es morgen aber noch mal checken.

**Comment by Ezechyel** [comment]
Hallo @Tonphis ,
ich habe es gestern Abend behoben, kann aber nicht sicher sagen wie.
Was ich getan habe: ich habe die Eingangsreferenzen der Tags gelöscht und neu angelegt. Dazu habe die MAC-Adressen aus der JSON-Antwort aus der Anfrage `http://loxberry/plugins/ble_scanner/?mode=normal` (siehe Anleitung des Plugins) kopiert und eingefügt und die Berechtigungen in der Config der Eingänge auf `Alle` gesetzt.

Gestern hat es funktioniert, heute noch nicht getestet.

Gruß Ezechyel
