### ISSUE TITLE
Fehler: Error reading general config! 

### ISSUE THREAD

**Issue by neminor** [Woersty/LoxBerry-Plugin-BLE-Scanner#9]
Bei mir erscheint beim Scannen folgende Fehlermeldung im Log:

2017-01-04 20:12:03 Error reading general config! [direct]
[04-Jan-2017 20:25:05 Europe/Berlin] PHP Warning:  syntax error, unexpected '!' in ../../../../config/system/general.cfg on line 16
 in /opt/loxberry/webfrontend/html/plugins/ble_scanner/index.php on line 136
2017-01-04 20:25:05 Error reading general config! [direct]
2017-01-04 20:31:29 [OK] Scan: 3 Tag(s) found [http://192.168.3.35/admin/index.cgi]

in der general.cfg steht an der Stelle die SSID des WLans "Fritz!Box". Bei anderen Plugins oder im Loxberry allgemein habe ich keine Probleme erkannt.

**Comment by Woersty** [comment]
In Anführungszeichen?
Michael müsste das wohl mal auf strict ändern.
Wer macht denn auch ein ! in die SSID?!

> in der general.cfg steht an der Stelle die SSID des WLans "Fritz!Box".

**Comment by neminor** [comment]
> In Anführungszeichen?

Nein, nicht in Anführungszeichen

> Michael müsste das wohl mal auf strict ändern.

Soll ich das extra im loxberry repository melden?

> Wer  macht denn auch ein ! in die SSID?!

AVM ;-) Genau genommen steht da Fritz!Box 7330 als SSID was die Standard SSID der Fritzbox ist.

**Comment by Woersty** [comment]
Geht es denn, wenn du den Wert in Anführungszeichen setzt?

Gruß

**Comment by neminor** [comment]
> Geht es denn, wenn du den Wert in Anführungszeichen setzt?

In der general.cfg editiert oder in der Loxberry UI geändert?

**Comment by neminor** [comment]
Ich habe die general.cfg angepasst so dass dort nun SSID="Fritz!Box 7330" (also mit Ausrufezeichen steht) und ein reboot gemacht. Nun funktioniert das Plugin fehlerfrei. 
M.E. sollte die Loxberry Config das aber automatisch handeln so dass auch die Standard-AVM SSIDs nicht auf ein Fehler laufen.

Deshalb würde ich es im loxberry repository eintragen oder?

**Comment by neminor** [comment]
Issue kann geschlossen werden, habe es hier erneut eingetragen:

https://github.com/mschlenstedt/Loxberry/issues/171
